#!/usr/bin/env python3
"""
Master SCP generation script for SR_CorrNet SS (Speech Separation).

Generates all SCP files needed by SS training/test configs into data/scp/.
Before running on a new server, edit the DB_PATHS section below.

LibriMix is generated by running `ss/create_scp_libri_8k.py` directly.

Usage:
    python generate_all_scp.py                    # Generate all SS SCPs
    python generate_all_scp.py wsj0_kmix whamr    # Generate specific datasets
    python generate_all_scp.py --list              # List available datasets

Datasets:
    wsj0_kmix   WSJ0-K-mix 2/3/4/5-speaker mixes
    wham        WHAM! noisy 2-speaker mixes (mono)
    whamr       WHAMR! reverberant 2-speaker mixes (mono)
    whamr_2ch   WHAMR! stereo 2-speaker mixes (2-channel)
"""

import os
import sys
from pathlib import Path


# ============================================================
# DB PATHS — Edit these paths for your server
# ============================================================
DB_PATHS = {
    # SS (Speech Separation)
    "wsj0_kmix":    "<EDIT_ME>/wsj0_kmix",
    "wham":         "<EDIT_ME>/WHAM",
    "whamr":        "<EDIT_ME>/WHAMR",
}

# ============================================================
# Output directory
# ============================================================
SCRIPT_DIR = Path(__file__).resolve().parent
SCP_DIR = SCRIPT_DIR.parent / "scp"


# ============================================================
# Core utility
# ============================================================

def write_scp(scp_path, data_dir, key_func=None, file_filter=None):
    """Walk data_dir and write SCP entries to scp_path.

    Args:
        scp_path:    Output .scp file path.
        data_dir:    Source data directory to walk.
        key_func:    (root, file) -> key string. Default: filename.
        file_filter: (file) -> bool. Default: accept all.

    Returns:
        Number of entries written, or -1 if data_dir not found.
    """
    if not os.path.isdir(data_dir):
        return -1

    os.makedirs(os.path.dirname(scp_path), exist_ok=True)
    count = 0
    with open(scp_path, 'w') as f:
        for root, dirs, files in os.walk(data_dir):
            files.sort()
            for file in files:
                if file_filter and not file_filter(file):
                    continue
                key = key_func(root, file) if key_func else file
                f.write(f"{key} {root}/{file}\n")
                count += 1
    return count


# ============================================================
# Key functions
# ============================================================

def key_path_file(root, file):
    """Key = 'root_filename'"""
    return f"{root}_{file}"


def key_stem(root, file):
    """Key = filename without extension"""
    return os.path.splitext(file)[0]


# ============================================================
# File filters
# ============================================================

def no_space(file):
    return ' ' not in file


def wav_no_space(file):
    return file.endswith('.wav') and ' ' not in file


def wav_only(file):
    return file.endswith('.wav')


# ============================================================
# Dataset generators
# ============================================================

def gen_wsj0_kmix():
    """WSJ0-K-mix 2/3/4/5 speakers (SS) -> scp_wsj0_mix_8k/"""
    db = DB_PATHS["wsj0_kmix"]
    results = {}
    for num_spk in [2, 3, 4, 5]:
        out = SCP_DIR / f"scp_wsj0_mix_8k/{num_spk}mix"
        root_dir = f"{db}/{num_spk}speakers/wav8k/min"
        for p in ['tr', 'cv', 'tt']:
            results[f"{num_spk}mix_{p}_mix"] = write_scp(
                str(out / f"{p}_mix.scp"), f"{root_dir}/{p}/mix")
            for i in range(1, num_spk + 1):
                results[f"{num_spk}mix_{p}_s{i}"] = write_scp(
                    str(out / f"{p}_s{i}.scp"), f"{root_dir}/{p}/s{i}")
    return results


def gen_wham():
    """WHAM (SS) -> scp_ss_8k_wham/"""
    db = DB_PATHS["wham"]
    out = SCP_DIR / "scp_ss_8k_wham"
    results = {}
    for p in ['tr', 'cv', 'tt']:
        results[f"{p}_mix"] = write_scp(str(out / f"{p}_mix.scp"), f"{db}/{p}/mix_both")
        results[f"{p}_s1"] = write_scp(str(out / f"{p}_s1.scp"), f"{db}/{p}/s1")
        results[f"{p}_s2"] = write_scp(str(out / f"{p}_s2.scp"), f"{db}/{p}/s2")
    results["tr_n"] = write_scp(str(out / "tr_n.scp"), f"{db}/tr/noise")
    return results


def gen_whamr():
    """WHAMR mono (SS) -> scp_ss_8k_whamr/"""
    db = DB_PATHS["whamr"]
    out = SCP_DIR / "scp_ss_8k_whamr"
    root = f"{db}/wav8k/min"
    results = {}
    for p in ['tr', 'cv', 'tt']:
        results[f"{p}_mix"] = write_scp(str(out / f"{p}_mix.scp"), f"{root}/{p}/mix_both_reverb")
        results[f"{p}_s1"] = write_scp(str(out / f"{p}_s1.scp"), f"{root}/{p}/s1_anechoic")
        results[f"{p}_s2"] = write_scp(str(out / f"{p}_s2.scp"), f"{root}/{p}/s2_anechoic")
    results["tr_s1_reverb"] = write_scp(str(out / "tr_s1_reverb.scp"), f"{root}/tr/s1_reverb")
    results["tr_s2_reverb"] = write_scp(str(out / "tr_s2_reverb.scp"), f"{root}/tr/s2_reverb")
    results["tr_n"] = write_scp(str(out / "tr_n.scp"), f"{root}/tr/noise")
    return results


def gen_whamr_2ch():
    """WHAMR stereo (SS) -> scp_ss_8k_whamr_2ch/"""
    db = DB_PATHS["whamr"]
    out = SCP_DIR / "scp_ss_8k_whamr_2ch"
    root = f"{db}/stereo/wav8k/min"
    results = {}
    for p in ['tr', 'cv', 'tt']:
        results[f"{p}_mix"] = write_scp(str(out / f"{p}_mix.scp"), f"{root}/{p}/mix_both_reverb")
        results[f"{p}_s1"] = write_scp(str(out / f"{p}_s1.scp"), f"{root}/{p}/s1_anechoic")
        results[f"{p}_s2"] = write_scp(str(out / f"{p}_s2.scp"), f"{root}/{p}/s2_anechoic")
    results["tr_s1_reverb"] = write_scp(str(out / "tr_s1_reverb.scp"), f"{root}/tr/s1_reverb")
    results["tr_s2_reverb"] = write_scp(str(out / "tr_s2_reverb.scp"), f"{root}/tr/s2_reverb")
    results["tr_n"] = write_scp(str(out / "tr_n.scp"), f"{root}/tr/noise")
    return results


# ============================================================
# Registry
# ============================================================

DATASETS = {
    # SS
    "wsj0_kmix":    ("SS", gen_wsj0_kmix),
    "wham":         ("SS", gen_wham),
    "whamr":        ("SS", gen_whamr),
    "whamr_2ch":    ("SS", gen_whamr_2ch),
}


def print_list():
    print("\nAvailable datasets:")
    print("-" * 50)
    found, missing = 0, 0
    for task in ["SS"]:
        print(f"\n  [{task}]")
        for name, (t, func) in DATASETS.items():
            if t == task:
                db_key = name if name != "whamr_2ch" else "whamr"
                db_path = DB_PATHS.get(db_key, "N/A")
                if os.path.isdir(db_path):
                    status = "\033[32m[OK]\033[0m"
                    found += 1
                else:
                    status = "\033[31m[NOT FOUND]\033[0m"
                    missing += 1
                print(f"    {name:15s} {status:s}  {db_path}")
    print(f"\n  Total: {found} found, {missing} not found")
    print()


def run_generator(name, func):
    print(f"\n{'='*50}")
    print(f"  Generating: {name} — {func.__doc__}")
    print(f"{'='*50}")

    results = func()
    ok, skip, total = 0, 0, 0
    for scp_name, count in results.items():
        total += 1
        if count < 0:
            print(f"  [SKIP] {scp_name} — source directory not found")
            skip += 1
        else:
            print(f"  [OK]   {scp_name}: {count} entries")
            ok += 1

    return ok, skip, total


def main():
    if "--list" in sys.argv:
        print_list()
        return

    # Determine which datasets to generate
    targets = [a for a in sys.argv[1:] if not a.startswith("-")]
    if not targets:
        targets = list(DATASETS.keys())

    invalid = [t for t in targets if t not in DATASETS]
    if invalid:
        print(f"Unknown dataset(s): {', '.join(invalid)}")
        print("Use --list to see available datasets.")
        sys.exit(1)

    print(f"SCP output directory: {SCP_DIR}")

    total_ok, total_skip = 0, 0
    for name in targets:
        task, func = DATASETS[name]
        ok, skip, _ = run_generator(name, func)
        total_ok += ok
        total_skip += skip

    print(f"\n{'='*50}")
    print(f"  Done: {total_ok} SCP files generated, {total_skip} skipped")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
